version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: mnp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: platform_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - platform-net

  manager:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.go
    container_name: mnp_manager
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: platform_db
      DB_PORT: 5432
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - db
    networks:
      - platform-net
    command: ["/usr/local/bin/manager"]

  node-test1:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.go
    container_name: mnp_node_1
    environment:
      MANAGER_IP: manager
      HOSTNAME: node-test-1
    depends_on:
      - manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - platform-net
    command: ["/usr/local/bin/node"]

  web:
    build:
      context: ../web
      dockerfile: ../deploy/Dockerfile.web
    container_name: mnp_web
    ports:
      - "80:80"
    networks:
      - platform-net

volumes:
  pgdata:

networks:
  platform-net:
    driver: bridge
